# Generated by Django 2.2.6 on 2019-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_adopter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescue',
            name='adopters',
            field=models.ManyToManyField(to='main_app.Adopter'),
        ),
    ]
